version: '3'

services:
  postgres:
    container_name: pdf_generator_db
    image: postgres:12.2
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 7702:5432

  spring-app:
    container_name: pdf_generator_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 7701:7701
    depends_on:
      - postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://pdf_generator_db:5432/postgres
      - front-end.address=http://dockerhost:8080

  client-app:
    container_name: pdf_generator_client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
