version: '3'

services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 7702:5432

  spring-app:
    build: ./
    ports:
      - 7701:7701
