version: '3'

services:
  postgres:
    container_name: pdf_generator_db
    image: postgres:12.2
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 7702:5432

  spring-app:
    container_name: pdf_generator_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 7701:7701
    depends_on:
      - postgres
